#pragma once

#define ALLOCATION_TYPE_FLAG_MASK (MEM_COMMIT | MEM_RESERVE | MEM_RESET | \
	MEM_RESET_UNDO | MEM_LARGE_PAGES | MEM_PHYSICAL | MEM_TOP_DOWN | MEM_WRITE_WATCH)

#define PROTECTION_TYPE_FLAG_MASK (PAGE_NOACCESS | PAGE_READONLY | PAGE_READWRITE | \
	PAGE_WRITECOPY | PAGE_EXECUTE | PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE | \
	PAGE_EXECUTE_WRITECOPY | PAGE_GUARD | PAGE_NOCACHE | PAGE_WRITECOMBINE | \
	PAGE_REVERT_TO_FILE_MAP | PAGE_TARGETS_NO_UPDATE | PAGE_TARGETS_INVALID)

typedef NTSTATUS(NTAPI* NtAllocateVirtualMemory_t)(
	HANDLE ProcessHandle,
	PVOID* BaseAddress,
	ULONG_PTR ZeroBits,
	PSIZE_T RegionSize,
	ULONG AllocationType,
	ULONG Protect
	);

typedef NTSTATUS(NTAPI* NtFreeVirtualMemory_t)(
	HANDLE ProcessHandle,
	PVOID* BaseAddress,
	PSIZE_T RegionSize,
	ULONG FreeType
	);

// THE VALUES FOR NAMES ARE GUESSED, BUT NAMES ARE CORRECT (THAT HOW ENUM SHOULD LOOK LIKE)
enum CONSOLE_TYPE {
	CONSOLE_TYPE_XBOX_ONE = 1,
	CONSOLE_TYPE_XBOX_ONE_S = 2,
	CONSOLE_TYPE_XBOX_ONE_X = 3,
	CONSOLE_TYPE_XBOX_ONE_X_DEVKIT = 4
};

typedef struct _SYSTEMOSVERSIONINFO {
	UINT8 MajorVersion;
	UINT8 MinorVersion;
	UINT16 BuildNumber;
	UINT16 Revision;
} SYSTEMOSVERSIONINFO, * LPSYSTEMOSVERSIONINFO;

typedef struct _PROCESSOR_SCHEDULING_STATISTICS {
	UINT64 RunningTime;
	UINT64 IdleTime;
	UINT64 GlobalTime;
} PROCESSOR_SCHEDULING_STATISTICS, * PPROCESSOR_SCHEDULING_STATISTICS;

typedef struct _TOOLINGMEMORYSTATUS {
	DWORD     dwLength;
	DWORD     dwReserved;
	DWORDLONG ullTotalMem;
	DWORDLONG ullAvailMem;
	DWORDLONG ulPeakUsage;
	DWORDLONG ullPageTableUsage;
} TOOLINGMEMORYSTATUS, * PTOOLINGMEMORYSTATUS, * LPTOOLINGMEMORYSTATUS;

typedef struct _TITLEMEMORYSTATUS {
	DWORD dwLength;
	DWORD dwReserved;
	DWORDLONG ullTotalMem;
	DWORDLONG ullAvailMem;
	DWORDLONG ullLegacyUsed;
	DWORDLONG ullLegacyPeak;
	DWORDLONG ullLegacyAvail;
	DWORDLONG ullTitleUsed;
	DWORDLONG ullTitleAvail;
} TITLEMEMORYSTATUS, * PTITLEMEMORYSTATUS, * LPTITLEMEMORYSTATUS;

__int64 sub_18001BB8C();

NTSTATUS sub_18001BCA0(HINSTANCE hInstance, DWORD forwardReason, LPVOID lpvReserved);

static CRITICAL_SECTION XMemSetAllocationHooksLock_X;